[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cp package-backend.json package.json", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server/dist/index.js"

[variables]
NODE_ENV = "production"
